server:
  port: 20020

spring:
  application:
    name: cloud-config-read
  rabbitmq:
    host: 192.168.8.131

logging:
  level:
    com:
      example:
        demo: debug

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

stuname: automatous
